global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eureka-server'
    static_configs:
      - targets: ['eureka-server:8761']
    metrics_path: '/actuator/prometheus'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'flight-service'
    static_configs:
      - targets: ['flight-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'seat-service'
    static_configs:
      - targets: ['seat-service:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8085']
    metrics_path: '/actuator/prometheus'

  - job_name: 'currency-service'
    static_configs:
      - targets: ['currency-service:8086']
    metrics_path: '/actuator/prometheus'